### ISSUE TITLE
External Coturn Server IP address family mismatch

### ISSUE THREAD

**Issue by olegokunevych** [elixir-webrtc/ex_ice#59]
We are trying to use `ex_ice` lib as dependency of `ex_webrtc` with Coturn server configured as following:
```
min-port=32355
max-port=65535
fingerprint
lt-cred-mech
syslog
log-file=/var/tmp/turn.log

user={user}:{pass}
relay-ip={local_ip}
external-ip={external_ip}/{local_ip}
realm={external_ip}
```
Coturn runs in the cloud behind NAT and configured to work with IPv4 addresses.
With TURN Server configured, app receives FunctionClauseError:
```
12:09:51.429 [error] pid=<0.978.0> mfa=:gen_server.error_info/8  GenServer #PID<0.978.0> terminating
** (FunctionClauseError) no function clause matching in anonymous fn/1 in ExICE.Priv.ICEAgent.create_relay_gathering_transactions/3
    (ex_ice 0.8.0) lib/ex_ice/priv/ice_agent.ex:890: anonymous fn({false, %ExTURN.Client{ref: #Reference<0.222363824.1241776130.184465>, uri: %ExSTUN.URI{scheme: :turn, host: "foo.bar.baz", port: 3478, transport: :udp}, turn_ip: {111, 222, 0, 33}, turn_port: 3478, username: "user", password: "password", realm: nil, nonce: nil, key: nil, state: :new, transactions: %{}, permissions: MapSet.new([]), addr_channel: %{}, channel_addr: %{}}, {11111, 22222, 33333, 44444, 5555, 66666, 77777, 88888}}) in ExICE.Priv.ICEAgent.create_relay_gathering_transactions/3
    (elixir 1.16.2) lib/enum.ex:4402: Enum.reject_list/2
    (ex_ice 0.8.0) lib/ex_ice/priv/ice_agent.ex:890: ExICE.Priv.ICEAgent.create_relay_gathering_transactions/3
    (ex_ice 0.8.0) lib/ex_ice/priv/ice_agent.ex:292: ExICE.Priv.ICEAgent.gather_candidates/1
    (ex_ice 0.8.0) lib/ex_ice/ice_agent.ex:316: ExICE.ICEAgent.handle_cast/2
    (stdlib 5.2) gen_server.erl:1121: :gen_server.try_handle_cast/3
    (stdlib 5.2) gen_server.erl:1183: :gen_server.handle_msg/6
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :gather_candidates}
```
Seems that TURN client has IPv4 ip while ICE Agent Socket has IPv6 ip family. Created a corresponding PR https://github.com/elixir-webrtc/ex_ice/pull/58 that handles error and skips relay gathering transaction in case of ip families mismatch, let me know if it make sense.

**Comment by mickel8** [comment]
Released in 0.8.1
